# Generated by Django 6.0.3 on 2026-03-12 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo_solucion', models.CharField(choices=[('sitio_web', 'Sitio Web'), ('aplicacion_movil', 'Aplicación Móvil'), ('automatizacion', 'Automatización'), ('sistema_escritorio', 'Sistema de Escritorio'), ('otro', 'Otro')], max_length=30)),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10)),
                ('estado', models.CharField(choices=[('pendiente_aprobacion', 'Pendiente de Aprobación'), ('publicado', 'Publicado'), ('en_desarrollo', 'En Desarrollo'), ('en_revision', 'En Revisión'), ('finalizado', 'Finalizado'), ('rechazado', 'Rechazado'), ('inactivo', 'Inactivo')], default='pendiente_aprobacion', max_length=25)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_aprobados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_empresa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
