# Generated by Django 6.0.3 on 2026-03-20 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_proyecto_vacantes_alter_proyecto_estado_and_more'),
    ]

    operations = [
        
    ]
