# Generated by Django 6.0.3 on 2026-03-24 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_alter_historialestadoproyecto_table_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='valoracion',
            name='rol_evaluador',
            field=models.CharField(choices=[('empresa', 'Empresa'), ('desarrollador', 'Desarrollador')], default='empresa', max_length=20),
        ),
        migrations.AlterField(
            model_name='valoracion',
            name='desarrollador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones_como_dev', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='valoracion',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones_como_empresa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='valoracion',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='proyectos.proyecto'),
        ),
        migrations.AlterUniqueTogether(
            name='valoracion',
            unique_together={('proyecto', 'rol_evaluador')},
        ),
        migrations.AlterModelTable(
            name='historialestadoproyecto',
            table='historial_estado_proyecto',
        ),
        migrations.AlterModelTable(
            name='proyecto',
            table='proyectos',
        ),
        migrations.AlterModelTable(
            name='valoracion',
            table='valoraciones',
        ),
    ]
