# Generated by Django 6.0.3 on 2026-03-25 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_valoracion_rol_evaluador_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialestadoproyecto',
            name='cambiado_por',
            field=models.ForeignKey(db_column='cambiado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historialestadoproyecto',
            name='proyecto',
            field=models.ForeignKey(db_column='proyecto_id', on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='proyectos.proyecto'),
        ),
        migrations.AlterField(
            model_name='valoracion',
            name='desarrollador',
            field=models.ForeignKey(db_column='desarrollador_id', on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones_como_dev', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='valoracion',
            name='empresa',
            field=models.ForeignKey(db_column='empresa_id', on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones_como_empresa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='valoracion',
            name='proyecto',
            field=models.ForeignKey(db_column='proyecto_id', on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='proyectos.proyecto'),
        ),
    ]
