# Generated by Django 6.0.3 on 2026-03-28 06:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0005_alter_historialestadoproyecto_cambiado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='valoracion',
            unique_together={('proyecto', 'desarrollador', 'rol_evaluador')},
        ),
    ]
