# Generated by Django 6.0.3 on 2026-03-20 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avances', '0001_initial'),
    ]

    operations = [
        # La tabla 'avances' ya existe en la BD con este nombre (importada del SQL original).
        # Esta migración se convierte en no-op para sincronizar el estado sin modificar la BD.
    ]
