# Generated by Django 6.0.3 on 2026-03-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avances', '0002_alter_avance_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avance',
            name='archivo_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterModelTable(
            name='avance',
            table='avances',
        ),
    ]
