# Generated by Django 6.0.5 on 2026-06-27 21:36

from django.db import migrations, models


def set_empty_string_for_null_urls(apps, schema_editor):
    Avance = apps.get_model('avances', 'Avance')
    Avance.objects.filter(archivo_url__isnull=True).update(archivo_url='')


class Migration(migrations.Migration):

    dependencies = [
        ('avances', '0007_alter_avance_entregable'),
    ]

    operations = [
        migrations.RunPython(set_empty_string_for_null_urls),
        migrations.AlterField(
            model_name='avance',
            name='archivo_url',
            field=models.CharField(max_length=500, blank=False),
        ),
    ]
