# Generated by Django 6.0.3 on 2026-03-16 03:07

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('contrataciones', '0001_initial'),
        ('proyectos', '0002_proyecto_vacantes_alter_proyecto_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratacion',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrataciones', to='proyectos.proyecto'),
        ),
    ]
