# Generated by Django 6.0.3 on 2026-03-20 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrataciones', '0002_alter_contratacion_proyecto'),
    ]

    operations = [
        # La tabla 'contrataciones' ya existe en la BD con este nombre.
        # No-op para sincronizar sin modificar la BD.
    ]
