# Generated by Django 6.0.3 on 2026-03-24 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postulaciones', '0002_alter_postulacion_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='postulacion',
            table='postulaciones',
        ),
    ]
