# Generated by Django 6.0.3 on 2026-03-20 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_fecha_nacimiento_and_more'),
    ]

    operations = [
        # Todos los cambios de esta migración ya están aplicados en la BD:
        # - AlterModelOptions (sin efecto en la BD)
        # - AddField 'nombre' -> ya existe la columna en usuarios_usuario
        # - AlterModelTable perfildesarrollador -> perfil_desarrollador (ya existe)
        # - AlterModelTable perfilempresa -> perfil_empresa (ya existe)
        # - AlterModelTable usuario -> usuarios (ya existe)
        # No-op para sincronizar sin modificar la BD.
    ]
