# Generated by Django 6.0.3 on 2026-04-03 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_perfilempresa_calificacion_promedio'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfildesarrollador',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/devs/'),
        ),
        migrations.AddField(
            model_name='perfildesarrollador',
            name='portafolio_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/empresas/'),
        ),
    ]
