# Generated by Django 6.0.3 on 2026-03-20 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favoritos', '0001_initial'),
    ]

    operations = [
        # La tabla 'favoritos' ya existe en la BD con este nombre.
        # No-op para sincronizar sin modificar la BD.
    ]
